name: shacl
 
on:
  workflow_dispatch:   
  push:
    branches:
      - main    
 
jobs:
  test:
    runs-on: ubuntu-latest 
    steps:  
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate against SHACL shape
        uses: konradhoeffner/shacl@v1
        with:
          shacl: myshaclfile.ttl
          data: TACIO.ttl  
  